
insert into  cob_ahorros..ah_tran_monet 
(tm_fecha,tm_secuencial,tm_cod_alterno,tm_tipo_tran,tm_filial,tm_oficina,tm_usuario,tm_terminal,tm_correccion,tm_sec_correccion,tm_origen,tm_nodo,tm_reentry,tm_signo,tm_fecha_ult_mov,tm_cta_banco,tm_valor,tm_chq_propios,tm_chq_offshore,tm_chq_locales,tm_chq_ot_plazas,tm_otros_valores,tm_remoto_ssn,tm_moneda,tm_efectivo,tm_indicador,tm_causa,tm_departamento,tm_saldo_lib,tm_saldo_contable,tm_saldo_disponible,tm_saldo_interes,tm_fecha_efec,tm_interes,tm_control,tm_ctadestino,tm_tipo_xfer,tm_estado,tm_concepto,tm_oficina_cta,tm_hora,tm_banco,tm_valor_comision,tm_prod_banc,tm_sector_cta,tm_tasa_iva,tm_valor_iva,tm_imprime_ndc,tm_documento,tm_origen_dv,tm_val_chq,tm_chq_ot_plazas_me,tm_destino_dv,tm_tarjeta,tm_tsn,tm_ssn_branch,tm_banca_cont,tm_factura,tm_canal,tm_pais_dv,tm_crefiscal,tm_engiro,tm_cotizacion,tm_moneda_re,tm_efectivo_re,tm_chq_propios_re,tm_chq_offshore_re,tm_chq_locales_re,tm_chq_exterior_re,tm_otros_valores_re,tm_compra_venta,tm_atm_server,tm_localidad,tm_autorizacion_cot,tm_cotizacion_dol)
select hm_fecha,hm_secuencial,hm_cod_alterno,hm_tipo_tran,hm_filial,hm_oficina,hm_usuario,hm_terminal,hm_correccion,hm_sec_correccion,hm_origen,hm_nodo,hm_reentry,hm_signo,hm_fecha_ult_mov,hm_cta_banco,hm_valor,hm_chq_propios,hm_chq_offshore,hm_chq_locales,hm_chq_ot_plazas,hm_otros_valores,hm_remoto_ssn,hm_moneda,hm_efectivo,hm_indicador,hm_causa,hm_departamento,hm_saldo_lib,hm_saldo_contable,hm_saldo_disponible,hm_saldo_interes,hm_fecha_efec,hm_interes,hm_control,hm_ctadestino,hm_tipo_xfer,hm_estado,hm_concepto,hm_oficina_cta,hm_hora,hm_banco,hm_valor_comision,hm_prod_banc,hm_sector_cta,hm_tasa_iva,hm_valor_iva,hm_imprime_ndc,hm_documento,hm_origen_dv,hm_val_chq,hm_chq_ot_plazas_me,hm_destin_dv,hm_tarjeta,hm_tsn,hm_ssn_branch,hm_banca_cont,hm_factura,hm_canal,hm_pais_dv,hm_crefiscal,hm_engiro,hm_cotizacion,hm_moneda_re,hm_efectivo_re,hm_chq_propios_re,hm_chq_offshore_re,hm_chq_locales_re,hm_chq_exterior_re,hm_otros_valores_re,hm_compra_venta,hm_atm_server,hm_localidad,hm_autorizacion_cot,hm_cotizacion_dol
from cob_ahorros_his..ah_his_movimiento
where hm_fecha  ='11/02/2017'





